# Generated by Django 3.0.3 on 2021-02-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rhub', '0004_auto_20210228_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='userid',
            field=models.CharField(max_length=100),
        ),
    ]
