# Generated by Django 3.0.3 on 2021-02-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rhub', '0005_auto_20210228_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='userid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
