# Generated by Django 3.0.3 on 2021-02-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rhub', '0006_auto_20210228_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='probability',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='sentiment',
            field=models.IntegerField(null=True),
        ),
    ]
