# Generated by Django 3.0.3 on 2021-03-03 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rhub', '0008_auto_20210303_1421'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='ReviewMovie',
        ),
    ]
