# Generated by Django 3.0.3 on 2021-03-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rhub', '0009_auto_20210303_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriesid', models.IntegerField()),
                ('userid', models.CharField(max_length=100, null=True)),
                ('review', models.CharField(max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sentiment', models.IntegerField(null=True)),
                ('probability', models.FloatField(null=True)),
            ],
        ),
    ]
