# Generated by Django 3.0.3 on 2021-03-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rhub', '0010_reviewseries'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageCount',
        ),
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
